trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade build setuptools twine
    python -m build
    pip install -r requirements.txt
  displayName: 'Install dependencies'


- script: |
    pytest
  displayName: 'pytest'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: mypythonappfeed

# Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
- script: |
    python -m twine upload -r "advmypythonappfeed" --config-file $(PYPIRC_PATH) dist/*
